resources:
  - ../../base
images:
  - name: web-content-api
    newTag: dev
patches:
  - target:
      kind: Deployment
      name: web-content-api
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: web-content-api
      spec:
        replicas: 1
